server:
port: 8086
spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/test

    username: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#spring.datasource.url=jdbc:postgresql://localhost:5432/book_system
#spring.datasource.username=root
#spring.datasource.password=postgres
#spring.datasource.driverClassName=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
